# Ansible Inventory for Vault SSH + PKI Demo
# This inventory shows how to use Vault SSH for authentication

webservers:
  hosts:
    web1.example.com:
      ansible_host: 192.168.1.10
    web2.example.com:
      ansible_host: 192.168.1.11
    web3.example.com:
      ansible_host: 192.168.1.12

dbservers:
  hosts:
    db1.example.com:
      ansible_host: 192.168.1.20
    db2.example.com:
      ansible_host: 192.168.1.21

all:
  vars:
    # Ansible configuration for Vault SSH
    ansible_user: ansible
    ansible_ssh_private_key_file: /tmp/vault-ssh-key
    ansible_ssh_certificate_file: /tmp/vault-ssh-key-cert.pub
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    # Vault configuration
    vault_addr: http://localhost:8200
    vault_namespace: ""

    # Application configuration
    app_domain: example.com
